namespace ArtfulAdventures.Data.Models.Enums;

public enum HashTagType
{
    Abstract,
    Anatomy,
    Animals_Wildlife,
    Anime_Manga,
    Automotive,
    ArchitecturalDesign,
    Art,
    Artist,
    Artwork,
    CharacterDesign,
    Comic,
    Creative,
    Drawing,
    DigitalАrt,
    DigitalPainting,
    DigitalDrawing,
    DigitalIllustration,
    DigitalPortrait,
    DigitalSketching,
    EnvironmentalDesign,
    FanArt,
    Fantasy,
    GameArt,
    Graffiti,
    Illustration,
    MechanicalDesign,
    Painting,
    PixelArt,
    Portrait,
    Props,
    Realism,
    ScienceFiction,
    Sketch,
    StreetArt,
    VectorArt,
    Watercolor,
    Weapons,
    UnrealEngine
}

